states_dir: "robocross/"
states:
  start: "StartState.py"
  moving: "MovingState.py"
  gpsfollow: "GPSFollowState.py"
  lanefollow: "LaneFollowState.py"
  stopped: "StoppedState.py"
  emergency: "EmergencyState.py"
  turn: "TurnState.py"
workers:
  lightswitch: "LightSwitchDetectorWorker.py"
  roadsign: "RoadSignDetectorWorker.py"
  ipm: "IPMWorker.py"
  semanticsegmentation: "SemanticSegmentationWorker.py"
  lanelinedetection: "LaneLineDetectionWorker.py"
  pathplanning: "PathPlanningWorker.py"
  behavioranalysis: "BehavioralAnalysisWorker.py"
  reedsshepp: "ReedsSheppPlanningWorker.py"
workerstates:
  start: ["semanticsegmentation", "ipm", "lanelinedetection", "roadsign"]
  moving: ["semanticsegmentation", "ipm", "lanelinedetection", "lightswitch", "roadsign", "behavioranalysis", "pathplanning"]
  lanefollow: ["semanticsegmentation", "ipm", "lanelinedetection", "lightswitch", "roadsign", "behavioranalysis", "pathplanning"]
  gpsfollow: ["semanticsegmentation", "ipm", "lanelinedetection", "lightswitch", "roadsign", "behavioranalysis", "pathplanning"]
  stopped: ["semanticsegmentation", "ipm", "lanelinedetection", "roadsign"]
  turn: ["semanticsegmentation", "ipm", "lanelinedetection", "reedsshepp"]
  emergency: []
transitions:
  start:
    start_move: ["moving"]
    stop: ["stopped"]
  gpsfollow:
    start_move: ["moving"]
    start_lane_follow: ["lanefollow"]
    stop: ["stopped", "emergency"]
    turn: ["turn"]
  moving:
    start_gps_follow: ["gpsfollow"] 
    start_lane_follow: ["lanefollow"]
    stop: ["stopped", "emergency"]
    turn: ["turn"]
  lanefollow:
    start_gps_follow: ["gpsfollow"] 
    start_move: ["moving"]
    stop: ["stopped", "emergency"]
    turn: ["turn"]
  stopped:
    start_move: ["moving"]
  emergency:
    reset: ["start"]
  turn:
    start_move: ["moving"]
    stop: ["stopped", "emergency"]
map-elements:
  - element:
    id: "start"
    name: !!str Точка старта
    ol-type: !!str Point
    color: !!str 00ff00
  - element:
    id: "turn"
    name: !!str Зона разворота
    ol-type: !!str Polygon
    color: !!str ffff00
  - element:
    id: "finish"
    name: !!str Зона  финиша
    ol-type: !!str Polygon
    color: !!str ff0000
  - element:
    id: "nolanes"
    name: !!str Зона движения без линий разметки 
    ol-type: !!str Polygon
    color: !!str 0000ff
  - element:
    id: "moving"
    name: !!str Путь следования
    ol-type: !!str LineString
    color: !!str 0000ff
  - element:
    id: "stop"
    name: !!str Зона остановки
    ol-type: !!str Polygon
    color: !!str 800080
  - element:
    id: "speed10"
    name: !!str Зона скорости 10
    ol-type: !!str Polygon
    color: !!str fe00f0
  - element:
    id: "speed20"
    name: !!str Зона скорости 20
    ol-type: !!str Polygon
    color: !!str fefcba
  - element:
    id: "speed30"
    name: !!str Зона скорости 30
    ol-type: !!str Polygon
    color: !!str aef0b0
  - element:
    id: "speed40"
    name: !!str Зона скорости 40
    ol-type: !!str Polygon
    color: !!str fe00cf