# lat: 48.38870275478814
# lon: 54.31585005003535
# mapfile: mf.geojson

lat: 43.638987354236185
lon: 56.335206573823854
mapfile: robocross.geojson

# lat: 43.638987354236185
# lon: 56.335206573823854
# mapfile: test_astar.geojson

# lat: 52.000441437135855
# lon: 55.81957703977085
# mapfile: terminal.geojson

# lat: 52.056359044407195
# lon: 55.83791784298242
# mapfile: test.geojson

# lat: 52.023696731776
# lon: 55.85129206068814
# mapfile: test2.geojson

# lat: 51.99936364777386
# lon: 55.81939263269305
# mapfile: test3.geojson

# lat: 52.00153648853302
# lon: 55.81928266212344
# mapfile: test4.geojson

# lat: 51.99949172325432
# lon: 55.81937695853412
# mapfile: parking.geojson

# lat: 52.00153648853302
# lon: 55.81928266212344
# mapfile: test5.geojson

# lat: 52.00153648853302
# lon: 55.81928266212344
# mapfile: test_parking.geojson
